name = "nexus17"
main = "bot.py"
compatibility_date = "2024-04-03"
compatibility_flags = ["python_workers"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "nexus"
# database_id = "YOUR_D1_DATABASE_ID"

[assets]
directory = "./public"
binding = "ASSETS"
