name = "nexus16"
main = "index.py"
compatibility_date = "2024-04-03"
compatibility_flags = ["python_workers"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "nexus"
database_id = "809930f5-93df-403d-82c5-14f777366d40"
